---
version: "3"
services:
 devopsdb:
   image: abhishekparla/myrepo:db
   ports:
     - "3306:3306"

 application:
   image: abhishekparla/myrepo:app
   ports:
     - "8080:8080"
   depends_on:
     - "devopsdb"
